---
- hosts: nodes
  become: true
  gather_facts: no
  tasks:      
  - name: stop if we have old docker container
    command: docker stop simple-devops-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi padrajucs/dockerimage
    ignore_errors: yes
    
  - name: pulling docker image
    command: docker pull padrajucs/dockerimage 

  - name: creating docker container
    command: docker run --rm -dit --name simple-devops-container -p 80:8080 padrajucs/dockerimage
   
 
   

